### ISSUE TITLE
Laravel 5.8 issues

### ISSUE THREAD

**Issue by fwartner** [orlyapps/nova-belongsto-depend#33]
Seems like it´s not working with L5.8 anymore. Something broke the Keys...

**Comment by Iprieto** [comment]
Hi! I just upgrade my Laravel to v5.8 and there is a change in the relations which is changing the getForeignKey method by getForeignKeyName method. I get this error when I try to run my v5.8 because Nova is using nova-belongsto-depend which is using getForeignKey method, so I change this call in vendor/orlyapps/nova-belongsto-depend/src/NovaBelongsToDepend.php's method "resolve" and now is working fine.

**Comment by orlyapps** [comment]
fixed with https://github.com/orlyapps/nova-belongsto-depend/commit/8082308de445a00cf1e38c990daa7b064c8acc10
